"""Tests for hypso.capture_types - L1BCapture/L1CCapture/L1DCapture/
L2ACapture, entered only via to_l1b()/to_l1c()/to_l1d()/to_l2a(). "What
level is this object" is a fact of its type here, not a tracked string -
see hypso/capture_types.py's module docstring and docs/architecture.rst's
"Cube memory" section.

The deprecated in-place generate_l1b_cube()/generate_l1c_cube()/
generate_l1d_cube() family (still what hypso-processing-pipeline calls) is
completely untouched by this - covered by the existing real-capture
regression suite (test_regression_real_capture.py), not duplicated here.
"""
import numpy as np
import pytest

from conftest import requires_real_capture
from hypso import capture_types

pytestmark = requires_real_capture


def test_to_l1b_returns_typed_object_and_leaves_self_untouched(satobj):
    l1b = satobj.to_l1b(coeff_type="moved")

    assert isinstance(l1b, capture_types.L1BCapture)
    assert not isinstance(l1b, type(satobj))
    assert not hasattr(l1b, "l1a_cube")
    assert not hasattr(l1b, "_l1a_cube")

    # self must be completely untouched
    assert satobj.l1a_cube is not None
    assert satobj.l1b_cube is not None  # already generated by the session fixture


def test_to_l1a_returns_typed_object_and_leaves_self_untouched(satobj):
    l1a = satobj.to_l1a()

    assert isinstance(l1a, capture_types.L1ACapture)
    assert not isinstance(l1a, type(satobj))
    assert not hasattr(l1a, "_l1a_cube")
    assert np.array_equal(l1a.cube.to_numpy(), satobj.l1a_cube.to_numpy(), equal_nan=True)

    # self must be completely untouched
    assert satobj.l1a_cube is not None


def test_to_l1b_from_l1a_matches_direct_to_l1b(satobj):
    # Two different source shapes into spawn_l1b: an L1ACapture (uniform
    # ._cube) and the old-style HypsoCapture (._l1a_cube) - must agree.
    l1a = satobj.to_l1a()
    l1b_via_l1a = l1a.to_l1b(coeff_type="moved")
    l1b_direct = satobj.to_l1b(coeff_type="moved")

    assert isinstance(l1b_via_l1a, capture_types.L1BCapture)
    assert not hasattr(l1b_via_l1a, "l1a_cube")
    # ._cube must be L1B's own calibrated data, not the inherited L1A cube
    # left over from spawning
    assert l1b_via_l1a._cube is not l1a._cube
    assert np.array_equal(l1b_via_l1a.cube.to_numpy(), l1b_direct.cube.to_numpy(), equal_nan=True)

    # l1a itself must be untouched by spawning l1b from it
    assert l1a.cube is not None


def test_l1a_convenience_one_hops_match_chained(satobj):
    l1a = satobj.to_l1a()

    l1c_one_hop = l1a.to_l1c(coeff_type="moved")
    l1c_chained = l1a.to_l1b(coeff_type="moved").to_l1c()
    assert np.array_equal(l1c_one_hop.cube.to_numpy(), l1c_chained.cube.to_numpy(), equal_nan=True)

    l1d_one_hop = l1a.to_l1d()
    l1d_chained = l1a.to_l1b().to_l1d()
    assert np.array_equal(l1d_one_hop.cube.to_numpy(), l1d_chained.cube.to_numpy(), equal_nan=True)


def test_to_l1c_relabels_l1b_data(satobj):
    l1b = satobj.to_l1b(coeff_type="moved")
    l1c = l1b.to_l1c()

    assert isinstance(l1c, capture_types.L1CCapture)
    assert l1c.cube.attrs.get("level") == "L1c"
    assert np.array_equal(l1c.cube.to_numpy(), l1b.cube.to_numpy(), equal_nan=True)
    # l1b itself must be untouched by spawning l1c from it
    assert l1b.cube.attrs.get("level") != "L1c"


def test_to_l1d_from_l1b_and_from_l1c_agree(satobj):
    l1b = satobj.to_l1b(coeff_type="moved")
    l1c = l1b.to_l1c()

    l1d_from_b = l1b.to_l1d()
    l1d_from_c = l1c.to_l1d()

    assert isinstance(l1d_from_b, capture_types.L1DCapture)
    assert isinstance(l1d_from_c, capture_types.L1DCapture)
    assert np.array_equal(l1d_from_b.cube.to_numpy(), l1d_from_c.cube.to_numpy(), equal_nan=True)


def test_hypso_capture_to_l1d_one_hop_matches_chained(satobj):
    chained = satobj.to_l1b(coeff_type="moved").to_l1d()
    one_hop = satobj.to_l1b(coeff_type="moved").to_l1d()

    assert np.array_equal(chained.cube.to_numpy(), one_hop.cube.to_numpy(), equal_nan=True)


def test_masked_cube_uniform_matches_masked_l1x_cube(satobj):
    l1b = satobj.to_l1b(coeff_type="moved")

    assert np.array_equal(l1b.masked_cube.to_numpy(), l1b.cube.to_numpy(), equal_nan=True)

    shape = l1b.spatial_dimensions
    l1b.land_mask = np.ones(shape, dtype=bool)
    assert np.isnan(l1b.masked_cube.to_numpy()).all()


def test_l2a_cube_property_single_correction(monkeypatch, satobj):
    l1b = satobj.to_l1b(coeff_type="moved")
    l1d = l1b.to_l1d()
    # l1d._l2a_cubes is already an independent copy (spawn_as copies it at
    # every hop) - clearing it here only affects this local object, not the
    # shared session-scoped satobj. Needed because satobj is shared with
    # other test files (e.g. conftest.py's written_nc_files fixture adds its
    # own "testac" correction directly onto satobj) - this test's premise
    # ("exactly one correction registered") only holds if we start clean.
    l1d._l2a_cubes.clear()

    def fake_open_output(self, target_satobj, **kwargs):
        # target_satobj is the freshly-spawned L2ACapture - its ._cube still
        # holds the aliased L1D data at this point (not deleted until after
        # a successful open_output), but its .cube PROPERTY already reads
        # _l2a_cubes (empty right now) - read the raw attribute here, not
        # the property, to get dummy L2A data to register.
        target_satobj._l2a_cubes["testac"] = target_satobj._cube.to_numpy()
        target_satobj._l2a_cubes["testac"].attrs["l2_variable_name"] = "chla"

    from hypso.ac.adapters import get_ac_adapter
    monkeypatch.setattr(type(get_ac_adapter("polymer")), "open_output", fake_open_output)

    l2a = l1d.to_l2a("polymer")

    assert isinstance(l2a, capture_types.L2ACapture)
    assert not hasattr(l2a, "_cube")
    assert list(l2a.l2a_cubes.keys()) == ["testac"]
    assert np.array_equal(l2a.cube.to_numpy(), l1d.cube.to_numpy(), equal_nan=True)

    with pytest.raises(ValueError, match="not defined for L2A"):
        l2a.masked_cube


def test_l2a_cube_property_ambiguous_raises(monkeypatch, satobj):
    # satobj is session-scoped and shared with other test files - some (e.g.
    # test_ac_subprocess.py, via conftest.py's written_nc_files fixture)
    # directly add their own L2A correction ("testac") onto it, so this
    # can't assume a clean slate. "a"/"b" are guaranteed-new keys added on
    # top of whatever's already there - that's enough to force >= 2 entries
    # and exercise the ambiguous-cube ValueError, without hardcoding a count.
    l1b = satobj.to_l1b(coeff_type="moved")
    l1d = l1b.to_l1d()

    def fake_open_output(self, target_satobj, **kwargs):
        target_satobj._l2a_cubes["a"] = target_satobj._cube.to_numpy()
        target_satobj._l2a_cubes["b"] = target_satobj._cube.to_numpy()

    from hypso.ac.adapters import get_ac_adapter
    monkeypatch.setattr(type(get_ac_adapter("polymer")), "open_output", fake_open_output)

    l2a = l1d.to_l2a("polymer")
    with pytest.raises(ValueError, match="L2A correction"):
        l2a.cube


def test_to_l2a_no_op_leaves_l1d_data_intact(monkeypatch, satobj):
    # adapter.open_output can legitimately no-op (missing output file) -
    # the returned object should keep its l1d cube rather than being
    # half-cleared. Compared against l1d's own (pre-existing, possibly
    # non-empty - see test_l2a_cube_property_ambiguous_raises's comment)
    # l2a_cubes rather than an assumed-empty {}, since satobj is shared
    # session-scoped state other test files also populate.
    l1b = satobj.to_l1b(coeff_type="moved")
    l1d = l1b.to_l1d()
    l1d_l2a_cubes_before = dict(l1d._l2a_cubes)

    from hypso.ac.adapters import get_ac_adapter
    monkeypatch.setattr(type(get_ac_adapter("polymer")), "open_output", lambda self, satobj, **kw: None)

    l2a = l1d.to_l2a("polymer")
    assert set(l2a.l2a_cubes) == set(l1d_l2a_cubes_before)
    assert l2a._cube is not None
    assert np.array_equal(l2a._cube.to_numpy(), l1d.cube.to_numpy(), equal_nan=True)
